### ISSUE TITLE
Auto-generated RobotLogger encountering "cannot be resolved or is not a field"

### ISSUE THREAD

**Issue by zeroClearAmerican** [wpilibsuite/2025Beta#20] opened 2024-11-01 00:59 UTC
**Describe the bug**
After converting our 2024 code to 2025, adding annotation logging, and resolving all build errors, attempts to run the robot code result in an error on program startup, stemming from the auto-generated Epilogue logger classes. 

The code can be built successfully using the `WPILib: Build robot code` command, and the error seems like it would occur during the build and not at runtime, so it's perplexing.

**To Reproduce**
1. Run the command "WPILib: Simulate Robot Code"
2. Note that the code builds without issue.
3. Select "Sim GUI"
4. Select "Continue" in the build failure notification.
5. Watch Sim GUI startup and immediately shutdown
6. Check `Debug: Main` terminal to see stack trace
  
 - Link to code: https://github.com/FRCTeam31/Tchaikovsky_2025Revamp/tree/drivetrain_sim

**Expected behavior**
The robot code would be expected to start successfully and enter Disabled mode

**Screenshots**
Here is the stack trace of the error:
```
Error at frc.robot.RobotLogger.update(RobotLogger.java:29): Unhandled exception: java.lang.Error: Unresolved compilation problem: 
        containerLogger cannot be resolved or is not a field

        at frc.robot.RobotLogger.update(RobotLogger.java:29)
        at frc.robot.RobotLogger.update(RobotLogger.java:1)
        at edu.wpi.first.epilogue.logging.ClassSpecificLogger.tryUpdate(ClassSpecificLogger.java:64)
        at edu.wpi.first.epilogue.Epilogue.update(Epilogue.java:34)
        at edu.wpi.first.epilogue.Epilogue.lambda$0(Epilogue.java:55)
        at edu.wpi.first.wpilibj.TimedRobot.startCompetition(TimedRobot.java:146)
        at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:350)
        at edu.wpi.first.wpilibj.RobotBase.lambda$startRobot$0(RobotBase.java:418)
        at java.base/java.lang.Thread.run(Unknown Source)
```
And a screenshot of the source:
![Image](https://github.com/user-attachments/assets/3cae4b5b-8897-4a77-8358-c5a4009920f7)

**Desktop:**
 - _OS:_ Windows 10
 - _OS Language:_ English
 - _Project Information:_ WPILib Information:
    Project Version: 2025.1.1-beta-1
    VS Code Version: 1.94.2
    WPILib Extension Version: 2025.1.1-beta-1
    C++ Extension Version: 1.22.9
    Java Extension Version: 1.36.2024092708
    Java Debug Extension Version: 0.58.2024090204
    Java Dependencies Extension Version 0.24.0
    Java Version: 17
    Java Location: C:\Users\Public\wpilib\2025\jdk
    Vendor Libraries:
        PathplannerLib (2025.0.0-beta-3.1)
        CTRE-Phoenix (v5) (5.34.0-beta-1)
        CTRE-Phoenix (v6) (25.0.0-beta-1)
        REVLib (2024.2.4)
        WPILib-New-Commands (1.0.0)

**roboRIO (please complete the following information if applicable):**
(simulation)

**Additional context**
n/a

**Comment by rzblue** [comment] 2024-11-01 02:17
We are aware of this issue and are investigating more options to fix or work around this. See [this comment](https://github.com/wpilibsuite/allwpilib/issues/7103#issuecomment-2439048528) for more info.

**Comment by zeroClearAmerican** [comment] 2024-11-01 03:13
Thanks for the update. Running `gradlew simulateJava` in the project's root directory is successfully starting the simulation for me.

**Comment by rzblue** [comment] 2024-11-12 17:53
Reopening until the issue is fixed in a release

**Comment by rzblue** [comment] 2024-11-21 07:15
Unfortunately, it appears that this can still happen on v2025.1.1-beta-2

**Comment by rzblue** [comment] 2024-11-22 02:16
We've identified a setting that appears to fix this in combination with the beta-2 fixes. Add the following to your project's `.vscode/settings.json`:
```
"java.import.gradle.annotationProcessing.enabled": false
```
The whole config should look something like this:
```
{
  "java.configuration.updateBuildConfiguration": "automatic",
  "java.server.launchMode": "Standard",
  "files.exclude": {
    "**/.git": true,
    "**/.svn": true,
    "**/.hg": true,
    "**/CVS": true,
    "**/.DS_Store": true,
    "bin/": true,
    "**/.classpath": true,
    "**/.project": true,
    "**/.settings": true,
    "**/.factorypath": true,
    "**/*~": true
  },
  "java.test.config": [
    {
      "name": "WPIlibUnitTests",
      "workingDirectory": "${workspaceFolder}/build/jni/release",
      "vmargs": [ "-Djava.library.path=${workspaceFolder}/build/jni/release" ],
      "env": {
        "LD_LIBRARY_PATH": "${workspaceFolder}/build/jni/release" ,
        "DYLD_LIBRARY_PATH": "${workspaceFolder}/build/jni/release"
      }
    },
  ],
  "java.test.defaultConfig": "WPIlibUnitTests",
  "java.import.gradle.annotationProcessing.enabled": false
}
```

**Comment by sciencewhiz** [comment] 2024-12-19 01:42
This is fixed in beta 3 for new projects

**Closed by sciencewhiz** 2024-12-19 01:42 UTC
Labels: bug, WPILib - Java, Pending
