### ISSUE TITLE
REV SparkMax throwing IllegalState exception during configuration

### ISSUE THREAD

**Issue by thenetworkgrinch** [wpilibsuite/2025Beta#37] opened 2024-11-11 22:11 UTC
**Describe the bug**
When configuring the SparkMax in simulation with `SparkMax.configure(SparkMaxConfig, ResetMode.kNoResetSafeParameters, PersistMode.kPersistParameters);` the internal `configure` method errors out.

**To Reproduce**
1. Clone YAGSL-Example [beta commit with known issue](https://github.com/BroncBotz3481/YAGSL-Example/tree/75f690c35bc2b4d524ec964ac5ff363f6b262477).
2. Run `gradlew :simulateJavaDebug`

 - Link to code:
 https://github.com/BroncBotz3481/YAGSL-Example/blob/75f690c35bc2b4d524ec964ac5ff363f6b262477/src/main/java/swervelib/motors/SparkMaxSwerve.java#L412-L419

**Expected behavior**

**Screenshots**
```
Error at com.revrobotics.spark.SparkBase.configure(SparkBase.java:276): Unhandled exception: java.lang.IllegalStateException: Parameter type mismatch for parameter id
	at com.revrobotics.spark.SparkBase.configure(SparkBase.java:276)
	at swervelib.motors.SparkMaxSwerve.burnFlash(SparkMaxSwerve.java:420)
```
The flattened options are
```
114,40800000
6,1
56,40800000
74,2
75,41400000
59,28
60,0
61,4E20
112,3D209CC8
113,3A2B51E6
70,2
71,14
16,0
17,0
19,BF800000
20,3F800000
9,1
13,39712C28
14,3456BF95
15,3F800000
160,14
193,0
188,1
189,0
190,0
158,A
191,0
159,14
```

**Desktop (please complete the following information if applicable):**
 - OS: Win 10
 - OS Language: English
 - Project Information: Running `:simulateJavaDebug` from gradle.

**Additional context**

**Comment by rzblue** [comment] 2024-11-11 22:15
Duplicate of #28, which was fixed in REVLib 2025.0.0-beta-2. What REVLib version are you using?

**Closed as completed** 2024-11-11 22:17 UTC
Labels: bug
