### ISSUE TITLE
REV Hardware Client crashes when connecting to USB devices

### ISSUE THREAD

**Issue by jwbonner** [wpilibsuite/2025Beta#31] opened 2024-11-08 17:27 UTC
When connecting over USB to a Spark Max, Spark Flex, or PDH, the main window of the hardware client closes with no error message. The window also closes immediately when reopening the application with a USB device connected.

This seems to occur regardless of device firmware version (tested with 2023 through 2025 beta), and I've recreated it on ~5 laptops running both Windows 10 and 11. It's possible to update firmware by placing devices in recovery mode, but the hardware client crashes again upon reconnecting to the flashed device (meaning that it cannot be configured).

The main process appears to continue running when the window closes, but I don't see any error messages for the main process or renderer process when enabling logging for Electron (just the normal status messages about checking for updates, etc).

Tested on hardware client version 2025 beta 0 and alpha 7.

**Comment by NoahAndrews** [comment] 2024-11-08 19:44
We don't see this issue, so I'm discussing this with @jwbonner directly. It would be helpful to know if anyone else is running into this issue as well.

**Comment by Kevin-OConnor** [comment] 2024-11-08 20:37
I don't see this issue but did see the other reported issue of not being able to set any parameters using HW Client with the Beta HW client and Beta firmware installed.

**Comment by GrahamSH-LLK** [comment] 2024-11-08 21:37
I believe I also ran into this or a similar issue when connecting/disconnecting USB devices, although the app would sometimes reopen.

**Comment by NoahAndrews** [comment] 2024-11-12 02:27
It appears this was caused by an outdated Visual C++ Redistributable. It'll be fixed in the next REV Hardware Client beta release.

@GrahamSH-LLK I'm pretty confident what you saw was a different issue. If you see it again, please report an issue through the small link in the bottom-right corner of the REV Hardware Client, and let me know that you've done so.

**Comment by NoahAndrews** [comment] 2024-11-15 03:40
Ok, I'll close this after we release the next RHC beta.

**Comment by srimanachanta** [comment] 2024-11-19 02:35
> It would be helpful to know if anyone else is running into this issue as well.

My team is also running into this problem on [REV Hardware Client 1.6.7-frcBeta2025.0](https://github.com/REVrobotics/REV-Software-Binaries/releases/tag/rhc-1.6.7-frcBeta2025.0). We can test out a new version of the hardware client when it is released and see if the issue is resolved.

**Closed** 2024-12-19 01:10 UTC
Labels: bug, REV Robotics, Pending
