### ISSUE TITLE
Commands added to NT throws "Commands that have been composed may not be added to another composition or scheduled individually"

### ISSUE THREAD

**Issue by isaacngkh** [wpilibsuite/2025Beta#38] opened 2024-11-12 01:20 UTC
**Describe the bug**
We imported our robot code from 2024 to 2025. As part of testing individual commands of a subsystem, we added these [commands ](https://github.com/gwhs/2024v2/blob/2025-beta/src/main/java/frc/robot/subsystems/Arm/ArmSubsystem.java#L65-L69)to [Shuffleboard](https://github.com/gwhs/2024v2/blob/2025-beta/src/main/java/frc/robot/subsystems/Arm/ArmSubsystem.java#L41-L42).

However, when we run the command from shuffleboard or in simulation, it would throw an exception.
![Image](https://github.com/user-attachments/assets/1be1b99c-ae60-42d6-8d89-d0c23ae2e1a6)

In WPILib 2024, this worked, but this no longer works in 2025 beta. 

I also noticed that the names of the commands are no longer displayed in simulation/shuffleboard; just SequentialCommandGroup
![Image](https://github.com/user-attachments/assets/df03d9d4-f3c0-4021-b9a6-52fa002fc8e1)
![Image](https://github.com/user-attachments/assets/b638fb2f-4273-4d17-885b-498736ac24e6)

Same code but in 2024
![Image](https://github.com/user-attachments/assets/d9f5c619-2792-40aa-b0af-0eead523af74)
![Image](https://github.com/user-attachments/assets/8523e14b-2315-4093-b69a-5a019d563905)

**To Reproduce**
1. Add command to shuffleboard
2. Trigger command in shuffleboard in simulation -> throw
Unhandled exception: java.lang.IllegalArgumentException: Commands that have been composed may not be added to another composition or scheduled individually!

 - Link to code (if applicable):
2025 beta: https://github.com/gwhs/2024v2/blob/2025-beta/src/main/java/frc/robot/subsystems/Arm/ArmSubsystem.java
2024 version: https://github.com/gwhs/2024v2/blob/rewrite/src/main/java/frc/robot/subsystems/Arm/ArmSubsystem.java

**Expected behavior**
Run the command when triggered from shuffleboard

**Desktop (please complete the following information if applicable):**
 - OS: Windows 11
 - OS Language: English, Turkish
 - Project Information: 
WPILib Information:
Project Version: 2025.1.1-beta-1
VS Code Version: 1.94.2
WPILib Extension Version: 2025.1.1-beta-1
C++ Extension Version: 1.22.9
Java Extension Version: 1.36.2024092708
Java Debug Extension Version: 0.58.2024090204
Java Dependencies Extension Version 0.24.0
Java Version: 17
Java Location: C:\Users\Public\wpilib\2025\jdk
Vendor Libraries:
    PathplannerLib (2025.0.0-beta-4)
    CTRE-Phoenix (v6) (25.0.0-beta-2)
    photonlib (v2025.0.0-beta-1)
    WPILib-New-Commands (1.0.0)

**roboRIO (please complete the following information if applicable):**
 - roboRIO 1 or 2?: N/A; simulation
 - Image version: [Use the roboRIO imaging tool or the WPILib team number setter to determine the image version]

**Comment by Gold856** [comment] 2024-11-12 01:59
This is the same as [wpilibsuite/allwpilib#7352](https://github.com/wpilibsuite/allwpilib/issues/7352) and should be fixed in the next beta release.

**Comment by rzblue** [comment] 2024-11-12 17:51
Reopening until the issue is fixed in a release

**Comment by rzblue** [comment] 2024-11-21 07:10
Fixed in v2025.1.1-beta-2

**Closed by rzblue** 2024-11-21 07:10 UTC
Labels: bug, Pending
